### ISSUE TITLE
islice does not work for infinite iterators

### ISSUE THREAD

**Issue by tgmeow** [nvie/itertools.js#255]
The current implementation of islice gets stuck in an infinite loop when the for...of tries to reach the end of the infinite iterator.

`const pred = slicePredicate(start, stop, step);
    for (const [i, value] of enumerate(iterable)) {
        if (pred(i)) {
            yield value;
        }
    }`

**Comment by nvie** [comment]
Feel free to submit a PR with a fix, and add a test case for it. Happy to merge the fix 👍
