### ISSUE TITLE
regenerator-runtime dependency missing

### ISSUE THREAD

**Issue by JimPatterson** [nvie/itertools.js#305]
The current package.json is assuming that since babel-runtime has a dependency on regenerator-runtime, it will be available for itertools to use.  That is correct when using NPM or Yarn, but [pnpm](https://pnpm.js.org/) uses a different structure where the node_modules tree is not flat.  In my case (webpack compiling a UI), I get:

    spa/ui_main test:  WEBPACK  Compiling...
    spa/ui_main test:  WEBPACK  Failed to compile with 4 error(s)
    spa/ui_main test: Error in /home/jimp/dtr_code/momentum/node_modules/.registry.npmjs.org/itertools/1.3.2/node_modules/itertools/more-itertools.js
    spa/ui_main test:   Module not found: 'regenerator-runtime' in '/home/jimp/dtr_code/momentum/node_modules/.registry.npmjs.org/itertools/1.3.2/node_modules/itertools'

**Comment by nvie** [comment]
Hi @JimPatterson — thanks for reporting this issue.  What would be your proposed fix for this?  I'm not sure what to change to support this, as I'm unfamiliar with pnpm.  Can you advice me or submit a PR?

**Comment by JimPatterson** [comment]
It should be as simple as adding regenerator-runtime to the dependencies so that it gets installed also, but I'll test it to verify that is the right fix.

**Comment by nvie** [comment]
Odd. `@babel/runtime` should automatically pull in `regenerator-runtime` because it's its dependency, see https://github.com/babel/babel/blob/v7.3.1/packages/babel-runtime/package.json#L12.  It's not a direct dependency itertools relies on directly, but an implementation detail of `@babel/runtime`.  It's weird that pnpm isn't installing that nested dependency when you install itertools (or @babel/runtime).

**Comment by JimPatterson** [comment]
I think it is a direct dependency.

    $ git grep import.*regenerator-runtime
    src/builtins.js:import regeneratorRuntime from 'regenerator-runtime';
    src/custom.js:import regeneratorRuntime from 'regenerator-runtime';
    src/itertools.js:import regeneratorRuntime from 'regenerator-runtime';
    src/more-itertools.js:import regeneratorRuntime from 'regenerator-runtime';

Those modules don't actually use that import (in fact there is a eslint disable for no-unused-vars), but the import means it must be resolvable from itertools.

Pnpm uses a non-flat structure for the node_modules tree and one of the side effects of that is that you can only import things you have actually declared as a dependency.  Babel would be able to import it because it did declare it where you linked above.

I don't know that I understand why it is imported but not used (maybe because the babel translated code uses it)?  In this case, maybe it should be a peerDependency?  Based on https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins/34645112#34645112, it might be that this fits that case.

**Comment by nvie** [comment]
You're right I think. I think these imports stemmed from before I switched to `@babel/runtime` (i.e. Babel 7).  Apparently these "useless imports" weren't harmful, but I can see how they are causing issues when used with pnpm now.  I just removed those imports and pushed those changes out to `itertools@next`.  Would you mind giving that version a shot and see if that removes your issues?  If so, I'll push this out as the next version.

Thanks for reporting this!

**Comment by JimPatterson** [comment]
That fixed the problem.  Thanks for all your work creating this package and the fix.

**Comment by nvie** [comment]
No problem! Thanks for reporting this. I just made v1.5.0 official on NPM: https://www.npmjs.com/package/itertools
