### ISSUE TITLE
Please add Typescript support

### ISSUE THREAD

**Issue by emchristiansen** [nvie/itertools.js#631]
I'd bet there's a big intersection between users who like iterator-style (functional-style) programming and those who like static types, so please add support for Typescript!
I'd love to use this library, as I really like Python's itertools API, but instead I'll have to use [iter-tools](https://www.npmjs.com/package/iter-tools) 😑

**Comment by nvie** [comment]
This was on my todo list for quite some time now. I just pushed out [v1.7.0](https://github.com/nvie/itertools.js/releases/tag/v1.7.0), which has full TypeScript support! Please let me know if you find a bug somewhere. Thanks for opening this issue. 💯
