### ISSUE TITLE
Proposal: Add `find` and `findValue` functions

### ISSUE THREAD

**Issue by brandonmcconnell** [nvie/itertools.js#859]
> **NOTE:** There is an upcoming TC39 proposal, [proposal-iterator-helpers](https://github.com/tc39/proposal-iterator-helpers), which will provide its own way to `run` a `find` function like the one(s) below, but until then, the below function(s) seek to accomplish the same with full safety.

In line with the other iterable functions, having a built-in function that can retrieve the first matched entry or value in an iterable based on an accessor and an optional final parameter for the desired return value would be very helpful.

Some iterables have a `values()` method to retrieve the values for that iterable. I think it could be useful to expose a separate method that accounts for that.

### Background helper functions and type helpers

There is probably something already like this used elsewhere in this package to use instead, but including it for the sake of completeness in my definitions and examples

```ts
type TransformFunction<T, U> = (params: T) => U;
type KeyOrTransform<T, U> = keyof T | TransformFunction<T, U>;
type PossiblyValuesIterable<T> = { values(): IterableIterator<T> } | Iterable<T>;
export function createObjectSearcher<T, U>(searchFnOrKey?: null): null;
export function createObjectSearcher<T, U>(
  searchFnOrKey: KeyOrTransform<T, U>
): TransformFunction<T, U>;
export function createObjectSearcher<T, U>(
  searchFnOrKey?: null | KeyOrTransform<T, U>
) {
  return typeof searchFnOrKey !== 'function' && searchFnOrKey != null
    ? (data: T) => data[searchFnOrKey as keyof T] as U
    : searchFnOrKey;
}
```

### `find` definition

```ts
/** Find first matching element from any iterable
 * @param iterable - The iterable to search
 * @param predicate - A function or key to extract the value to search for
 * @param useValues - Whether to use `iterable.values()` instead of the iterable itself
 * @returns The first matching element or undefined
 *
 * @example retrieving a value (from `iterable.values()`) where useValues=false
 * find(values, v => value[1])[1]
 * @example retrieving a value (from `iterable.values()`) where useValues=true
 * find(values, v => value, true)
 */
export const find = <T, U extends (value: T) => unknown, K extends keyof T>(
  iterable: PossiblyValuesIterable<T>,
  predicate: U | K,
  useValues: boolean = false
): T | undefined => {
  const values =
    useValues && 'values' in iterable
      ? iterable.values()
      : (iterable as Iterable<T>);
  const accessor = createObjectSearcher(predicate);
  for (const item of values) {
    if (accessor(item)) {
      return item;
    }
  }
  return undefined;
};
```

### `findValue` definition

`findValue` is essentially a light abstraction around `find` for better readability

```ts
/** Same as find but presets the useValue param to true, as a decorator
 * @see find
 * @example BEFORE: using `find` to retrieve a value using `useValues=true` param
 * find(values, v => value, true)
 * @example AFTER: using `findValue` to retrieve a value
 * findValue(values, v => value)
 *
 * ? About the same length to type `true` directly, but this is more readable
 */
export const findValue = <T, U extends (value: T) => unknown, K extends keyof T>(
  iterable: PossiblyValuesIterable<T>,
  predicate: U | K
): T | undefined => {
  return find(iterable, predicate, true);
};
```

**Note:** when using `find` with `useValues=true` or using `findValue`, this function will use the `.values()` iterator for its iteration rather than the original iterator parameter value itself, if the iterator has a `.values()` iterator.

## Usage

To use the `find` and `findValue` function(s), pass in the iterable, an accessor function or a string representing a property name, and optionally a desired value function or a boolean. The function will iterate over the iterable and return the first matched value based on the accessor function or property.

Here are some examples:

### Example 1: Using a property name as accessor

```js
const data = [
  { id: 1, name: "Alice" },
  { id: 2, name: "Bob" },
  { id: 3, name: "Charlie" },
];

// `find` and `findValue` would yield the same result in this example

const result = findValue(data, 'name');
console.log(result); // { id: 1, name: "Alice" }
```

### Example 2: Using a custom accessor function

```js
const data = [
  { id: 1, score: 95 },
  { id: 2, score: 85 },
  { id: 3, score: 75 },
];

// `find` and `findValue` would yield the same result in this example

const result = findValue(data, (d) => d.score >= 90);
console.log(result); // { id: 1, score: 95 }
```

### Example 3: Specifying a desired value function

```js
const data = [
  { id: 1, score: 95 },
  { id: 2, score: 85 },
  { id: 3, score: 75 },
];

// `find` and `findValue` would yield the same result in this example

const result = findValue(data, (d) => d.score >= 90)?.id;
console.log(result); // 1
```

### Example 4: Specifying a desired value property name

```js
const data = [
  { id: 1, score: 95 },
  { id: 2, score: 85 },
  { id: 3, score: 75 },
];

// `find` and `findValue` would yield the same result in this example

const result = findValue(data, (d) => d.score >= 90)?.id;
console.log(result); // 1
```

### Example 5: Comparing `find` and `findValue` when iterating over a Map

```js
const data = new Map([
  [1, { name: "Alice", age: 30 }],
  [2, { name: "Bob", age: 25 }],
  [3, { name: "Charlie", age: 28 }],
]);

// `find` and `findValue` would NOT yield the same result in this example

// using `find` with a Map will iterate over the Map entries directly, with `useValues=false`
const result = find(data, (d) => d[1].age >= 30)?.[1].name;

// using `find` with `useValues=true` will iterate over the .values() iterator
const result = find(data, (d) => d.age >= 30, true)?.name;

// `findValue` is equivalent to—but arguably more readbale than—using `find` with `useValues=true`
const result = findValue(data, (d) => d.age >= 30)?.name;
console.log(result); // "Alice"
```

**Comment by nvie** [comment]
Hi @brandonmcconnell — thanks for writing up such a great proposal! I like the `find()` name, because it matches the upcoming `.find()` method on iterables. Can't wait for that TC39 proposal to land. It will make iterables so much easier to work with out of the box.

Are you aware of the [`first()` itertool](https://github.com/nvie/itertools.js#first)? It seems to be doing what you're proposing for `find()` already, not? (But it will not work with the convenience string based field acccessor, which I'm not a big fan of. To me `x => x.name` is almost as short and just as readable as `'name'`, but less magic.)

If you want to iterate over the values iterator, I don't think we'll have to add extra support for that in the form of a `useValues=true` config option, or a `findValue()` helper. Instead, you can just pass it a different iterator to walk over, right? Or am I missing a use case?

```ts
const data = new Map([
  [1, { name: "Alice", age: 30 }],
  [2, { name: "Bob", age: 25 }],
  [3, { name: "Charlie", age: 28 }],
]);

console.log(first(data, ([key, value]) => value.age >= 30));
console.log(first(data.values(), (d) => d.age >= 30));
console.log(first(data.values(), (d) => d.age >= 30));
```

That said, I think I like the `find()` name more than I like `first()`. The `first()` name came from Python, but in JavaScript, `find()` is definitely the more common name. I apologize if that name made you overlook the existing itertool and write this proposal in the first place 🙈 !  I'm happy to add it as an alias.

**Comment by brandonmcconnell** [comment]
Good thoughts al around, and yes, `first()` works exactly as I was intending for. Would you consider adding an alias of `first()` for `find()`? If this lib is meant as a pure polyfill of another lib that uses the `first` name, I totally understand though.

Regardless, your comments resolve this issue, so I'll close it. Thanks!

**Comment by nvie** [comment]
Yes, I think `find()` is a better name than `first()`, so I will add the alias in. I'm planning to make a few minor updates to this library soon (in the next week or two) – so thank you!
